# Generated by Django 2.1.5 on 2019-12-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_musicinstancereservation_takeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicinstancereservation',
            old_name='takeout',
            new_name='takenout',
        ),
    ]
