# Generated by Django 3.0.3 on 2020-02-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_musicinstancereservation_duedate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'permissions': (('can_browse_catalog', 'Can see what the music library has to offer'), ('can_see_availability', 'Can see whether a piece is available'), ('can_self_reserve', 'Can make a reservation for themself'), ('can_any_reserve', 'Can make reservations on behalf of other users'), ('can_issue', 'Can set reservation as borrowed'), ('can_return', 'Can mark borrowed music as now returned'), ('can_see_reservation_detail', 'Can see who has reserved or borrowed an instance'))},
        ),
    ]
