# Generated by Django 3.0.3 on 2020-02-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200215_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinstancereservation',
            name='returned',
            field=models.BooleanField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='musicinstancereservation',
            name='takenout',
            field=models.BooleanField(blank=True, max_length=5),
        ),
    ]
