# Generated by Django 3.0.3 on 2020-02-17 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20200216_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicinstancereservation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a musical genre (e.g. Jazz, Classical, Pop)', max_length=200),
        ),
        migrations.AlterField(
            model_name='musicinstancereservation',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musicinstancereservation',
            name='takenout',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityTimestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('activityCode', models.CharField(choices=[('res', 'Reserve'), ('bor', 'Borrow'), ('can', 'Cancel Res'), ('ret', 'Return'), ('ren', 'Renew')], help_text='The activity being logged', max_length=4)),
                ('composer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Composer')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Music')),
                ('musicInstance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MusicInstance')),
                ('musicInstanceReservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MusicInstanceReservation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
