# Generated by Django 3.0.3 on 2020-02-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0009_auto_20200217_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'permissions': (('can_browse_catalog', 'Can see what the music library has to offer'), ('can_see_availability', 'Can see whether a piece is available'), ('can_self_reserve', 'Can make a reservation for themself'), ('can_any_reserve', 'Can make reservations on behalf of other users'), ('can_issue', 'Can set reservation as borrowed'), ('can_return', 'Can mark borrowed music as now returned'), ('can_see_reservation_detail', 'Can see who has reserved or borrowed an instance'), ('is_admin', 'Can see admin pages'))},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Music')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
