# Generated by Django 3.0.3 on 2020-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200219_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='isbn',
        ),
        migrations.AddField(
            model_name='music',
            name='barcode',
            field=models.CharField(default='1122334', help_text='the library unique reference code for this  piece', max_length=13, verbose_name='barcode'),
            preserve_default=False,
        ),
    ]
