# Generated by Django 3.0.3 on 2020-02-22 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200219_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
