# Generated by Django 3.0.3 on 2020-02-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200223_1634'),
        ('catalog', '0013_auto_20200224_1443'),
    ]

    operations = [
    ]
