# Generated by Django 2.1.5 on 2019-07-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20190722_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicinstance',
            name='imprint',
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this music', to='catalog.Genre'),
        ),
    ]
