# Generated by Django 2.1.5 on 2019-08-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20190723_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Music availability', max_length=1),
        ),
    ]
