# Generated by Django 2.1.5 on 2019-08-07 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_auto_20190807_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('o', 'On loan'), ('ov', 'Overdue'), ('r', 'Returned')], default='r', help_text='Music availability', max_length=1)),
                ('musicid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Music')),
            ],
        ),
    ]
